- id: '1517092740693'
  alias: Sätt på Receiver när CCA börjar spela
  trigger:
  - entity_id: media_player.vardagsrum_audio
    from: idle
    platform: state
    to: playing
  - entity_id: media_player.vardagsrum_audio
    from: 'off'
    platform: state
    to: playing
  - entity_id: media_player.vardagsrum_audio
    from: paused
    platform: state
    to: playing
  - entity_id: media_player.home
    from: idle
    platform: state
    to: playing
  - entity_id: media_player.home
    from: 'off'
    platform: state
    to: playing
  - entity_id: media_player.home
    from: paused
    platform: state
    to: playing
  condition:
  - condition: state
    entity_id: media_player.onkyo
    state: 'off'
  action:
  - data:
      entity_id: media_player.onkyo
    service: media_player.turn_on
  - data:
      entity_id: media_player.onkyo
      source: ChromeCast Audio
    service: media_player.select_source

- id: '1562962609944'
  alias: Set theme at startup
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: Dark - Blue
    service: frontend.set_theme

- id: '1640075647638'
  alias: Keep Tuya Alive
  description: Keep tuya alive-reload every 80 minutes
  trigger:
  - platform: time_pattern
    hours: /1
  condition: []
  action:
  - service: homeassistant.reload_config_entry
    target:
      entity_id:
      - switch.eluttag_framsidan
  mode: single

- id: '2'
  alias: "Slå på LG TV"
  trigger:
    - platform: webostv.turn_on
      entity_id: media_player.lg_tv
  action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: !secret lg_mac_address
