- id: '1513546699606'
  alias: Tänd i matsal och hall
  trigger:
  - event: sunset
    offset: '15'
    platform: sun
  condition: []
  action:
  - data:
      brightness: 1
      color_temp: 370
      entity_id: light.bordslampa_group
    service: light.turn_on
  - data:
      brightness: 1
      color_temp: 370
      entity_id: light.hall_group
    service: light.turn_on
- id: '1513546699607'
  alias: Släck i matsal och hall
  trigger:
  - at: '23:02:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: light.bordslampa_group
    service: light.turn_off
  - data:
      entity_id: light.hall_group
    service: light.turn_off
- id: '1515350394630'
  alias: Släck ljusen när hemmet är tomt
  trigger:
  - entity_id: device_tracker.izac_xr
    for: '15'
    from: home
    platform: state
    to: not_home
  - entity_id: device_tracker.katrin_zagerholm_iphone
    for: '15'
    from: home
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: device_tracker.izac_xr
    state: not_home
  - condition: state
    entity_id: device_tracker.katrin_zagerholm_iphone
    state: not_home
  action:
  - data:
      entity_id: group.interior_lights
    service: light.turn_off
  - data:
      entity_id: group.interior_lights
    service: switch.turn_off
- action:
  - data:
      brightness: 1
      color_temp: 370
      entity_id: group.hall_lights
    service: light.turn_on
  alias: Tänd i hallen när någon kommer hem
  condition:
  - after: 06:00
    before: 01:00
    condition: time
  id: '1515595191018'
  trigger:
  - entity_id: device_tracker.izac7
    from: not_home
    platform: state
    to: home
  - entity_id: device_tracker.katrinzlmiphone
    from: not_home
    platform: state
    to: home
- action:
  - data:
      entity_id: group.hall_lights
    service: light.toggle
  alias: Tänd/släck i hallen vid knapptryck
  condition: []
  id: '1515869879592'
  trigger:
  - event_data:
      event: 1002
    event_type: deconz_event
    platform: event
- id: '1517092740693'
  alias: Sätt på Receiver när CCA börjar spela
  trigger:
  - entity_id: media_player.vardagsrum_audio
    from: idle
    platform: state
    to: playing
  - entity_id: media_player.vardagsrum_audio
    from: 'off'
    platform: state
    to: playing
  - entity_id: media_player.vardagsrum_audio
    from: paused
    platform: state
    to: playing
  - entity_id: media_player.home
    from: idle
    platform: state
    to: playing
  - entity_id: media_player.home
    from: 'off'
    platform: state
    to: playing
  - entity_id: media_player.home
    from: paused
    platform: state
    to: playing
  condition:
  - condition: state
    entity_id: media_player.onkyo
    state: 'off'
  action:
  - data:
      entity_id: media_player.onkyo
    service: media_player.turn_on
  - data:
      entity_id: media_player.onkyo
      source: ChromeCast Audio
    service: media_player.select_source
- action:
  - data:
      brightness: 1
      color_temp: 370
      entity_id: group.hall_lights
    service: light.turn_on
  alias: Tänd i hallen när dörren öppnas
  condition:
  - condition: state
    entity_id: device_tracker.izac7
    state: not_home
  - condition: state
    entity_id: device_tracker.katrinzlmiphone
    state: not_home
  id: '1521402321538'
  trigger:
  - entity_id: binary_sensor.ytterdorr
    from: 'off'
    platform: state
    to: 'on'
- id: '1522260319277'
  alias: Släck ljusen vid knapptryck
  trigger:
  - event_data:
      event: 2002
      id: knapp_entre
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: group.interior_lights
    service: light.turn_off
  - data:
      entity_id: group.interior_lights
    service: switch.turn_off
- action:
  - data:
      mac: 14:C9:13:82:46:82
    service: wake_on_lan.send_magic_packet
  - data:
      entity_id: media_player.lg_tv
    service: media_player.turn_on
  - wait_template: '{{ is_state(''media_player.lg_tv'', ''on'') }}'
    timeout: 00:00:30
  - data:
      entity_id: media_player.onkyo
    service: media_player.turn_on
  - wait_template: '{{ is_state(''media_player.onkyo'', ''on'') }}'
    timeout: 00:00:10
  - delay: 00:00:05
  - data:
      entity_id: media_player.onkyo
      source: Xbox
    service: media_player.select_source
  alias: Sätt på Receiver och TV när Xbox startar
  condition: []
  id: '1522350994697'
  trigger:
  - entity_id: device_tracker.xboxone
    from: 'off'
    platform: state
    to: 'on'
- id: '1545939407622'
  alias: Tänd nattduksbordslampor på kvällen om ingen är hemma
  trigger:
  - at: '22:03:00'
    platform: time
  condition:
  - condition: state
    entity_id: device_tracker.izac_xr
    state: not_home
  - condition: state
    entity_id: device_tracker.katrin_zagerholm_iphone
    state: not_home
  action:
  - data:
      brightness: 1
      color_temp: 370
      entity_id: light.isaclampan
    service: light.turn_on
  - data:
      brightness: 1
      color_temp: 370
      entity_id: light.kattylampan
    service: light.turn_on
- id: '1545939407623'
  alias: Släck nattduksbordslampor
  trigger:
  - at: '23:17:00'
    platform: time
  - at: 09:30:00
    platform: time
  condition: []
  action:
  - device_id: c7e72dbf51b643bb8e05f14e1bc599c4
    domain: light
    entity_id: light.isaclampan
    type: turn_off
  - device_id: 0440e6ef522c4711bd685f9c5a4e8ccb
    domain: light
    entity_id: light.kattylampan
    type: turn_off
- id: '1548063790184'
  alias: Tänd utebelysning innan skymning
  trigger:
  - below: '3'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  condition: []
  action:
  - data:
      entity_id:
      - group.outdoor_lights
      - light.light_terrace
    service: light.turn_on
- id: '1548063879836'
  alias: Släck utebelysning efter soluppgång
  trigger:
  - above: '2'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  condition: []
  action:
  - data:
      entity_id:
      - group.outdoor_lights
      - light.light_terrace
    service: light.turn_off
- id: '1552666721388'
  alias: Stäng av Receiver och TV vid HASS omstart
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:00:30
  - data:
      entity_id: media_player.onkyo
    service: media_player.turn_off
  - data:
      entity_id: media_player.lg_tv
    service: media_player.turn_off
- id: '1553273554685'
  alias: Aktivera mys kl 18:30
  trigger:
  - at: '18:30'
    platform: time
  condition: []
  action:
  - data:
      entity_id: scene.mys
    service: scene.turn_on
- id: '1555532536199'
  alias: Släck i vardagsrummet på kvällen om ingen är hemma
  trigger:
  - at: '22:37'
    platform: time
  condition:
  - condition: state
    entity_id: device_tracker.izac_xr
    state: not_home
  - condition: state
    entity_id: device_tracker.katrin_zagerholm_iphone
    state: not_home
  action:
  - data:
      entity_id: group.livingroom_lights
    service: light.turn_off
  - data:
      entity_id: group.livingroom_lights
    service: switch.turn_off
- id: '1559243971442'
  alias: Notify at door bell
  trigger:
  - entity_id: switch.tryckknapp_dorrklocka
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Någon ringde på dörrklockan!
      title: Dörrklockan
    service: notify.ios_izac_xr
  - data:
      message: Någon ringde på dörrklockan!
      title: Dörrklockan
    service: notify.ios_katrin_zagerholm_iphone
- id: '1562962609944'
  alias: Set theme at startup
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: Dark - Blue
    service: frontend.set_theme
- id: '1571204350505'
  alias: Notify iZac train 07:00 delayed
  description: ''
  trigger:
  - platform: template
    value_template: '{{ is_state('' sensor.tag_07_00_mot_gbg_c.departure_state '',
      ''delayed'') }}'
  condition:
  - condition: state
    entity_id: device_tracker.izac_xr
    state: home
  action:
  - data:
      message: Tåg 07:00 mot GBG C är försenat!
    service: notify.ios_izac_xr
- id: '1571596848861'
  alias: Mute sovrum
  description: ''
  trigger:
  - at: '18:00'
    platform: time
  condition: []
  action:
  - alias: ''
    data:
      entity_id: media_player.sovrum
      is_volume_muted: true
    service: media_player.volume_mute
- id: '1571597115624'
  alias: Unmute sovrum
  description: ''
  trigger:
  - at: 08:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: media_player.sovrum
      is_volume_muted: false
    service: media_player.volume_mute
- id: '1573327010133'
  alias: Tänd nattduksbordslampor på helgen
  description: ''
  trigger:
  - at: 08:30:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - data:
      brightness: 1
      entity_id: light.sanglampa_isac
    service: light.turn_on
  - data:
      brightness: 1
      entity_id: light.sanglampa_katrin
    service: light.turn_on
- id: '1574281607937'
  alias: Tänd växtbelysning
  description: ''
  trigger:
  - at: 07:00
    platform: time
  condition: []
  action:
  - alias: ''
    data:
      entity_id: light.growing_light_storage
    service: light.turn_on
- id: '1574281717704'
  alias: Släck växtbelysning
  description: ''
  trigger:
  - at: '21:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: light.growing_light_storage
    service: light.turn_off
- id: '1574365327804'
  alias: Släck i barnrum vid knapptryck
  description: ''
  trigger:
  - event_data:
      event: 2002
      id: knapp_barnrum
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id:
      - light.cloudlight
      - light.balloonlight
    service: light.turn_off
- id: '1576431925954'
  alias: Släck mysbelysning efter midnatt
  description: ''
  trigger:
  - at: 01:00
    platform: time
  condition: []
  action:
  - data:
      entity_id:
      - group.livingroom_lights
      - group.office_lights
    service: light.turn_off
- id: '1580248008016'
  alias: Aktivera Läggdags på vardagar
  description: ''
  trigger:
  - at: '21:45'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - scene: scene.laggdags
- id: '1581233409836'
  alias: Aktivera morgonstund
  description: ''
  trigger:
  - at: 06:30
    platform: time
  condition: []
  action:
  - entity_id: scene.morgonstund
    service: scene.turn_on
- id: '1581239976166'
  alias: Stäng av Onkyo när lampor släcks efter 22:00
  description: ''
  trigger:
  - entity_id: group.interior_lights
    from: 'on'
    platform: state
    to: 'off'
  - at: '22:00'
    platform: time
  condition:
  - after: '22:00'
    before: 06:00
    condition: time
  - condition: state
    entity_id: group.interior_lights
    state: 'off'
  action:
  - entity_id: media_player.onkyo
    service: media_player.turn_off
- id: '1582709437132'
  alias: Släck inomhus kl 10:00
  description: ''
  trigger:
  - at: '10:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id:
      - group.interior_lights
    service: light.turn_off
