- platform: ping
  name: "router"
  host: 192.168.1.1
  count: 1
  scan_interval: 10

- platform: ping
  name: "google"
  host: www.google.com
  count: 1
  scan_interval: 10

# - platform: workday
#   name: "workday_today"
#   country: SE
  
# - platform: workday
#   name: "workday_tomorrow"
#   country: SE
#   days_offset: 1

- platform: template
  sensors:
    water_heater_heating_enabled:
      unique_id: zgr_water_heater_heating_enabled
      friendly_name: "VVB aktiverad"
      value_template: "{{ is_state('switch.vvb_fas_1','on') or is_state('switch.vvb_fas_2','on') or is_state('sensor.vvb_fas_3','on')}}"
      icon_template: mdi:lightning-bolt