media_player:
  - platform: onkyo
    host: 192.168.1.41
    name: Onkyo
    sources:
      dvd: 'Apple TV'
      tv: 'LG TV'
      network: 'Spotify'
      cd: 'ChromeCast Audio'
      game: 'Xbox'
      strm-box: 'Chromecast Ultra'
      pc: 'WiiU'

spotcast:
  sp_dc: !secret kat_sp_dc
  sp_key: !secret kat_sp_key


wake_on_lan:

 
system_health:

mobile_app:

homekit:
  filter:
    include_domains:
      - alarm_control_panel
      - light
      - media_player
      - sensor
    include_entities:
      - switch.eluttag_kontor
      - switch.lff10r_heater
      - switch.lff10r_engine
      - lock.lff10r_door_lock
    exclude_entities:
      - light.hall_group
      - light.bordslampa_group
  entity_config:
    alarm_control_panel.home:
      code: !secret sec_alarm_code

# Google Assistant integration
google_assistant:
  project_id: !secret google_assistant_proj_id
  service_account: !include zagerholm-hass.json
#  report_state: true
  exposed_domains:
    - sensor
    - light
    - lock
    - scene
  entity_config:
    light.hall_1:
      expose: false
    light.hall_2:
      expose: false
    light.hall_3:
      expose: false
    light.hall_4:
      expose: false
    light.hall_group:
      name: Hall
    switch.eluttag_kontor:
      expose: true
    light.bordslampa_1:
      expose: false
    light.bordslampa_2:
      expose: false
    light.bordslampa_3:
      expose: false
    light.kont_taklampa:
      expose: false
    light.vardagsrum:
      expose: false


  
tellstick:
  host: core-tellstick
  port: [50800, 50801]
    
ifttt:
  key: !secret ifttt_key

hassio:

shelly:
  discovery: true  #add all devices (default)
  username: !secret shelly_username
  password: !secret shelly_password
  devices:  #configure devices
    - id: "E09806950E60"
      light_switch: true  #add this switch as a light
      name: "Belysning framsida"
    - id: "55C96F-1"
      light_switch: true  #add this switch as a light
      name: "Belysning garageport"
    - id: "55C96F-2"
      light_switch: true  #add this switch as a light
      name: "Taklampa garage"
    - id: "c39945"
      light_switch: false  #add this switch as a light
      name: "Shelly Plug 1"
    - id: "3C6105E35569"
      light_switch: true  #add this switch as a light
      name: "Taklampa vardagsrum"

# Enable the use of python scripts
pyscript:

homeassistant:
  # Name of the location where Home Assistant is running
  name: ZagerHome
  # Location required to calculate the time the sun rises and sets.
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 54
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml
  external_url: !secret external_url
  currency: SEK
  country: SE
  
my:
  
energy:

utility_meter:
  grid_consumption_energy_daily:
    unique_id: zgr_daily_energy_usage
    source: sensor.power_usage
    cycle: daily
    name: Daily energy
  grid_consumption_energy_monthly:
    unique_id: zgr_monthly_energy_usage
    source: sensor.power_usage
    cycle: monthly
    name: Monthly energy
  backside_water_usage_daily:
    unique_id: zgr_daily_backside_water_usage
    source: sensor.vattenflode
    cycle: daily
    name: Backside daily water usage
  backside_water_usage_monthly:
    unique_id: zgr_monthly_backside_water_usage
    source: sensor.vattenflode
    cycle: monthly
    name: Backside monthly water usage
  backside_water_usage_yearly:
    unique_id: zgr_yearly_backside_water_usage
    source: sensor.vattenflode
    cycle: yearly
    name: Backside yearly water usage

#hacs:
#  token: !secret hacs_token

zone:
  # This will override the default home zone
  - name: Home
    latitude: !secret lat
    longitude: !secret long
    radius: 100
    icon: mdi:account-multiple

# Enables the frontend
frontend:
  themes: !include themes.yaml
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

# Enables configuration UI
config:

# Delete old data from recorder
recorder:
  purge_keep_days: 2

# Settings for https
http:
  # For extra security set this to only accept connections on localhost if NGINX is on the same machine
  # Uncommenting this will mean that you can only reach Home Assistant using the proxy, not directly via IP from other clients.
  # server_host: 127.0.0.1
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
  trusted_proxies: !secret trusted_proxies
  
  #ssl_certificate: /ssl/fullchain.pem
  #ssl_key: /ssl/privkey.pem

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - switch
      - light
      - sun
    entities:
      - sensor.google
      - sensor.router
      - device_tracker.izac_xr
      - device_tracker.katrin_zagerholm_iphone
      - device_tracker.katrinsipad
      - binary_sensor.altandorr
      - binary_sensor.google
      - binary_sensor.router
  exclude:
    domains:
      - media_player
      - automation

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Log deCONZ event to detect button events
logger:
   default: info
#   logs:
#      homeassistant.components.pyscript: debug
#      custom_components.pyscript: debug
#      # Uncomment the below to get deCONZ button events
#      pydeconz: debug
#      homeassistant.components.deconz: debug
#      homeassistant.components.sector_alarm: debug

mqtt:
  sensor:
    - name: "RaspberryPi Borg Backup"
      state_topic: "home-assistant/rpiborgbackup/status"

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    
# ios:
#   actions:
#     - name: SVT1
#       background_color: "#0363F4"
#       label:
#         text: "Titta på SVT1"
#         color: "#ffffff"
#       icon:
#         icon: television
#         color: "#000000"

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
light: !include lights.yaml
scene: !include scenes.yaml
switch: !include switches.yaml
binary_sensor: !include binary_sensors.yaml
