binary_sensor:
  - platform: ping
    host: 192.168.1.1
    name: router
    count: 1
    scan_interval: 10
  - platform: ping
    host: www.google.com
    name: google
    count: 1
    scan_interval: 10

asuswrt:
    host: 192.168.1.1
    username: !secret asus_username
    password: !secret asus_password
    
apple_tv:

media_player:
  - platform: onkyo
    host: 192.168.1.42
    name: Onkyo
    sources:
      bd-dvd: 'Apple TV'
      tv-cd: 'LG TV'
      network: 'Spotify'
      cd: 'ChromeCast Audio'
      game: 'Xbox'
  - platform: webostv
    host: 192.168.1.43
    name: LG TV
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: 14:C9:13:82:46:82

sector_alarm:
  email: !secret sec_username
  password: !secret sec_password
  alarm_id: !secret sec_alam_id
#  code: <Your pin code to asm/disarm, optional>
  thermometers: false
  alarm_panel: true

wake_on_lan:        
 
system_health:

ios:

homekit:
  filter:
    include_domains:
      - alarm_control_panel
      - light
      - media_player
      - switch
      - sensor

volvooncall:
  username: !secret voc_username
  password: !secret voc_password

tellduslive:
  host: 192.168.1.92
  scan_interval: 5
  
tellstick:
  host: core-tellstick
  port: [50800, 50801]
    
ifttt:
  key: !secret ifttt_key

hassio:  

homeassistant:
  # Name of the location where Home Assistant is running
  name: ZagerHome
  # Location required to calculate the time the sun rises and sets.
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 54
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml
  
hacs:
  token: !secret hacs_token

zone:
  # This will override the default home zone
  - name: Home
    latitude: !secret lat
    longitude: !secret long
    radius: 100
    icon: mdi:account-multiple
    track_ios: false

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

# Delete old data from recorder
recorder:
  purge_interval: 2
  purge_keep_days: 2

http:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - switch
      - light
      - sun
    entities:
      - sensor.google
      - sensor.router
      - device_tracker.izac_xr
      - device_tracker.katrin_zagerholm_iphone
      - device_tracker.katrinsipad
      - device_tracker.dlinkipcam
      - binary_sensor.altandorr
      - binary_sensor.google
      - binary_sensor.router
      - binary_sensor.kok_balkongdorr
      - binary_sensor.kont_balkongdorr
  exclude:
    domains:
      - media_player
      - automation

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Log deCONZ event to detect button events
#logger:
#   default: warning
#   logs:
#      # Change the below to debug to get button events
#      pydeconz: warning
#      homeassistant.components.deconz: warning
#      homeassistant.components.sector_alarm: debug
#      homeassistant.components.tellduslive_custom: debug

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
light: !include lights.yaml
