binary_sensor:
  - platform: ping
    host: 192.168.1.1
    name: router
    count: 1
    scan_interval: 10
  - platform: ping
    host: www.google.com
    name: google
    count: 1
    scan_interval: 10
  - platform: workday
    name: workday_today
    country: SE
  - platform: workday
    name: workday_tomorrow
    country: SE
    days_offset: 1
    
climate:
  - platform: adax
    account_id: !secret adax_account_id # replace with your account ID (see Adax WiFi app, Account Section)
    password: !secret adax_password # replace with your remote user password (see Adax WiFi app, Account Section)

asuswrt:
    host: 192.168.1.1
    username: !secret asus_username
    password: !secret asus_password
    interface: vlan1
    sensors:
      - devices
      - upload
      - download
      - upload_speed
      - download_speed
    
media_player:
  - platform: onkyo
    host: 192.168.1.42
    name: Onkyo
    sources:
      bd-dvd: 'Apple TV'
      tv-cd: 'LG TV'
      network: 'Spotify'
      cd: 'ChromeCast Audio'
      game: 'Xbox'

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

#spotify:
#  client_id: !secret spotify_client_id
#  client_secret: !secret spotify_client_secret
        
webostv:
    name: LG TV
    host: 192.168.1.43
    #other settings
    turn_on_action:
        service: wake_on_lan.send_magic_packet
        data:
          mac: !secret lg_mac_address
    customize:
        sources:
          - LiveTV
          - Onkyo

sector_alarm:
  email: !secret sec_username
  password: !secret sec_password
  alarm_id: !secret sec_alarm_id
#  code: <Your pin code to asm/disarm, optional>
  thermometers: false
  alarm_panel: true

wake_on_lan:

#influxdb:
#  host: a0d7b954-influxdb
#  port: 8086
#  database: !secret influxdb_database
#  username: !secret influxdb_username
#  password: !secret influxdb_password
#  max_retries: 3
#  default_measurement: state
 
system_health:

mobile_app:

homekit:
  filter:
    include_domains:
      - alarm_control_panel
      - light
      - media_player
      - sensor
    include_entities:
      - switch.eluttag_kontor
      - switch.lff10r_heater
      - switch.lff10r_engine
      - lock.lff10r_door_lock
    exclude_entities:
      - light.hall_group
      - light.bordslampa_group
  entity_config:
    alarm_control_panel.home:
      code: !secret sec_alarm_code
      
# Google Assistant integration
google_assistant:
  project_id: !secret google_assistant_proj_id
  service_account: !include zagerholm-hass.json
#  report_state: true
  exposed_domains:
    - sensor
    - light
    - lock
    - scene
  entity_config:
    light.hall_1:
      expose: false
    light.hall_2:
      expose: false
    light.hall_3:
      expose: false
    light.hall_4:
      expose: false
    light.hall_group:
      name: Hall
    switch.eluttag_kontor:
      expose: true
    light.bordslampa_1:
      expose: false
    light.bordslampa_2:
      expose: false
    light.bordslampa_3:
      expose: false
    light.kont_taklampa:
      expose: false
    light.vardagsrum:
      expose: false

volvooncall:
  username: !secret voc_username
  password: !secret voc_password
  
tellstick:
  host: core-tellstick
  port: [50800, 50801]
    
ifttt:
  key: !secret ifttt_key

hassio:

shelly:
  discovery: true  #add all devices (default)
  username: !secret shelly_username
  password: !secret shelly_password
  sensors: #sensors to show, can be override on each device
    - all #show all sensors
  devices:  #configure devices
    - id: "E09806950E60"
      light_switch: true  #add this switch as a light
    - id: "55C96F"
      light_switch: true  #add this switch as a light

# Enable the use of python scripts
pyscript:

homeassistant:
  # Name of the location where Home Assistant is running
  name: ZagerHome
  # Location required to calculate the time the sun rises and sets.
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 54
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml
  external_url: "https://home.zagerholm.net:8123"
  
hacs:
  token: !secret hacs_token

zone:
  # This will override the default home zone
  - name: Home
    latitude: !secret lat
    longitude: !secret long
    radius: 100
    icon: mdi:account-multiple

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

# Delete old data from recorder
recorder:
  purge_keep_days: 2

# Settings for https
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - switch
      - light
      - sun
    entities:
      - sensor.google
      - sensor.router
      - device_tracker.izac_xr
      - device_tracker.katrin_zagerholm_iphone
      - device_tracker.katrinsipad
      - binary_sensor.altandorr
      - binary_sensor.google
      - binary_sensor.router
  exclude:
    domains:
      - media_player
      - automation

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Log deCONZ event to detect button events
logger:
   default: warning
   logs:
      homeassistant.components.pyscript: info
#      # Uncomment the below to get deCONZ button events
#      pydeconz: debug
#      homeassistant.components.deconz: debug
#      homeassistant.components.sector_alarm: debug

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    
ios:
  actions:
    - name: SVT1
      background_color: "#0363F4"
      label:
        text: "Titta på SVT1"
        color: "#ffffff"
      icon:
        icon: television
        color: "#000000"

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
light: !include lights.yaml
scene: !include scenes.yaml
