- platform: template
  lights:
    shelf_light_office:
      friendly_name: "Hyllampa kontor"
      value_template: '{{ states.switch.uttag2.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.uttag2
      turn_off:
        service: switch.turn_off
        entity_id: switch.uttag2
    vitrine_diningroom:
      friendly_name: "Vitrinskåp matsal"
      value_template: '{{ states.switch.vitrinskap.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.vitrinskap
      turn_off:
        service: switch.turn_off
        entity_id: switch.vitrinskap
    growing_light_storage:
      friendly_name: "Växtbelysning förråd"
      value_template: '{{ states.switch.vaxtbelysning_forrad.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.vaxtbelysning_forrad
      turn_off:
        service: switch.turn_off
        entity_id: switch.vaxtbelysning_forrad
    light_terrace:
      friendly_name: "Ljusslinga altan"
      value_template: '{{ states.switch.ljusslinga_altan.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.ljusslinga_altan
      turn_off:
        service: switch.turn_off
        entity_id: switch.ljusslinga_altan
    window_light_middle:
      friendly_name: "Fönsterlampa mitten"
      value_template: '{{ states.switch.uttag3.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.uttag3
      turn_off:
        service: switch.turn_off
        entity_id: switch.uttag3