- platform: template
  lights:
    wallamp_livingroom:
      friendly_name: "Vägglampa vardagsrum"
      value_template: '{{ states.switch.uttag1_vardagsrum.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.uttag1_vardagsrum
      turn_off:
        service: switch.turn_off
        entity_id: switch.uttag1_vardagsrum
    window_lights_livingroom:
      friendly_name: "Fönsterlampor vardagsrum"
      value_template: '{{ states.switch.uttag2_vardagsrum.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.uttag2_vardagsrum
      turn_off:
        service: switch.turn_off
        entity_id: switch.uttag2_vardagsrum
    golden_light_livingroom:
      friendly_name: "Guldlampa vardagsrum"
      value_template: '{{ states.switch.guldlampa.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.guldlampa
      turn_off:
        service: switch.turn_off
        entity_id: switch.guldlampa
    vitrine_diningrroom:
      friendly_name: "Vitrinskåp matsal"
      value_template: '{{ states.switch.vitrinskap.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.vitrinskap
      turn_off:
        service: switch.turn_off
        entity_id: switch.vitrinskap
    window_light_office:
      friendly_name: "Fönsterlampa kontor"
      value_template: '{{ states.switch.fonsterlampa_kontor.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.fonsterlampa_kontor
      turn_off:
        service: switch.turn_off
        entity_id: switch.fonsterlampa_kontor
    shelf_light_office:
      friendly_name: "Hyllampa kontor"
      value_template: '{{ states.switch.hyllampa_kontor.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.hyllampa_kontor
      turn_off:
        service: switch.turn_off
        entity_id: switch.hyllampa_kontor
    growing_light_storage:
      friendly_name: "Växtbelysning förråd"
      value_template: '{{ states.switch.vaxtbelysning_forrad.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.vaxtbelysning_forrad
      turn_off:
        service: switch.turn_off
        entity_id: switch.vaxtbelysning_forrad
    light_terrace:
      friendly_name: "Ljusslinga altan"
      value_template: '{{ states.switch.ljusslinga_altan.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.ljusslinga_altan
      turn_off:
        service: switch.turn_off
        entity_id: switch.ljusslinga_altan

# Light groups
- platform: group
  name: Bordslampa_group
  entities:
    - light.bordslampa_1
    - light.bordslampa_2
    - light.bordslampa_3

- platform: group
  name: Hall_group
  entities:
    - light.hall_1
    - light.hall_2
    - light.hall_3
    - light.hall_4 