- platform: template
  lights:
    shelf_light_office:
      friendly_name: "Hyllampa kontor"
      value_template: '{{ states.switch.uttag2.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.uttag2
      turn_off:
        service: switch.turn_off
        entity_id: switch.uttag2
    vitrine_diningroom:
      friendly_name: "Vitrinskåp matsal"
      value_template: '{{ states.switch.vitrinskap_switch.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.vitrinskap_switch
      turn_off:
        service: switch.turn_off
        entity_id: switch.vitrinskap_switch
    growing_light_storage:
      friendly_name: "Växtbelysning förråd"
      value_template: '{{ states.switch.vaxtbelysning_forrad.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.vaxtbelysning_forrad
      turn_off:
        service: switch.turn_off
        entity_id: switch.vaxtbelysning_forrad
    light_terrace:
      friendly_name: "Ljusslinga altan"
      value_template: '{{ states.switch.ljusslinga_altan.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.ljusslinga_altan
      turn_off:
        service: switch.turn_off
        entity_id: switch.ljusslinga_altan
    xmas_light_front:
      friendly_name: "Julbelysning framsida"
      value_template: '{{ states.switch.julbelysning_framsida.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.julbelysning_framsida
      turn_off:
        service: switch.turn_off
        entity_id: switch.julbelysning_framsida
    growing_light_dining_area:
      friendly_name: "Växtbelysning matsal"
      value_template: '{{ states.switch.uttag3.state }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.uttag3
      turn_off:
        service: switch.turn_off
        entity_id: switch.uttag3
#    xmas_tree:
#      friendly_name: "Julgran"
#      value_template: '{{ states.switch.uttag3.state }}'
#      turn_on:
#        service: switch.turn_on
#        entity_id: switch.uttag3
#      turn_off:
#        service: switch.turn_off
#        entity_id: switch.uttag3
- platform: group
  name: Sänglampor
  entities:
    - light.sanglampa_katrin
    - light.sanglampa_isac
- platform: group
  name: Barnrum
  entities:
    - light.ballonglampa
    - light.molnlampa
- platform: group
  name: Vardagsrum
  entities:
    - light.golvlampa
    - light.vagglampa
    - light.fonsterlampa_hoger
    - light.fonsterlampa_mitten
    - light.fonsterlampa_vanster
    - light.guldlampa