- platform: template
  switches:
    media_equipment:
      friendly_name: "Mediautrustning"
      value_template: "{{ states('switch.shelly_plug_1') }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.shelly_plug_1
      turn_off:
        service: switch.turn_off
        entity_id: switch.shelly_plug_1
    fireplace_fan:
      friendly_name: "Fläktar eldstad"
      value_template: "{{ states('switch.uttag2') }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.uttag2
      turn_off:
        service: switch.turn_off
        entity_id: switch.uttag2
#    onkyo_receiver:
#       friendly_name: "Onkyo Receiver"
#       value_template: '{{ states('switch.uttag5') }}'
#      turn_on:
#        service: switch.turn_on
#        entity_id: switch.uttag5
#      turn_off:
#        service: switch.turn_off
#        entity_id: switch.uttag5
