esphome:
  name: esphome-temp-reader

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret temp_reader_api_encryption_key

ota:
  password: !secret temp_reader_ota_password


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Temp-Reader"
    password: "RDIRJ63U2pWb"

captive_portal:
  
# DHT11 sensor
sensor:
  - platform: dht
    pin: 2
    temperature:
      name: "Test Temperature"
    humidity:
      name: "Test Humidity"
    update_interval: 10s