esphome:
  name: water-flow-meter

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret water_flow_meter_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water-Flow-Meter"
    password: "u0aB7A7gDTmn"

captive_portal:

# Enable Web server.
web_server:
  port: 80
  
# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time
  
# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: Water Flow Meter Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: Water Flow Meter IP
    ssid:
      name: Water Flow Meter SSID
    bssid:
      name: Water Flow Meter BSSID
      
# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Water Flow Meter Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: Water Flow Meter WiFi Signal
    update_interval: 60s

  - platform: pulse_counter
    pin: 4
    name: "Vattenflöde"
    unit_of_measurement: "l/min"
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    filters:
      - multiply: 0.0018  # From Amazon: 554 or 596 pulses per litre. 1 / 554 = factor of 0.0018 to get litres
    update_interval: 2s
    
# Exposed switches.
switch:
  # Switch to restart the water flow meter.
  - platform: restart
    name: Water Flow Meter Restart
    
status_led:
  pin:
    number: GPIO02
    inverted: true
